name: Love Awareness Arts
favicon: null
layout_spectrum: 0.8012474575079978
typography_spectrum: 0.2578587895259261
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.06769704213365912
  lightness: 0.9345198983792216
  saturation: 0.30689977295696735
  rhythmicContrast: 0.9658838240429759
purpose: []
